### PR TITLE
Added feature to input multi-sequence FASTA file.

### PR DESCRIPTION
**Pull request by stevin-wilson**
Since most Python ML libraries are integrated closely with Numpy, I have edited the code to output Protvec representations as NumPy arrays. 

I have also added a function to handle multi-sequence FASTA file as input and output a NumPy array with axis 0 being the sample axis. The function also outputs a .tsv file indicating the index for each sequence in the sample axis and a txt file indicating the sequences for which Protvec representations could not be computed.

I have also made the edit as suggested by the user, savagej, in the pull requests section.

Please let me know if additional edits are required. Thank you.

### CODE REVIEW

**Comment by kyu999** [comment]
Thank you for your cooperation!
I'll check it in a week :)

**Comment by kyu999** [comment]
It seems great overall, but need to write some tests to guarantee the codes work well.
If it's ok with you, would you write them?

**Comment by stevin-wilson** [comment]
Sure, I will do that in a week. Thank you

**Comment by stevin-wilson** [comment]
Hi kyu999

I have added few tests for the function that outputs biovec representation for each sequence in a FASTA file. Please let me know if more tests are needed.

Thank you and I wish you good health

**Pull request merged**
